version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: vamsi-task
        LoadBalancerInfo:
          ContainerName: vamsi-repo
          ContainerPort: 8080
