version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    ECR_REPO: public.ecr.aws/z8i7v1n4/vamsi-repo
    CONTAINER_NAME: vamsi-repo
    S3_BUCKET: vamsi-deploy-artifacts
    S3_KEY: ecs/deployment.zip

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo IMAGE_TAG=$IMAGE_TAG

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG $ECR_REPO:latest

  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push $ECR_REPO:$IMAGE_TAG
      - docker push $ECR_REPO:latest

      - echo Writing imagedefinitions.json...
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$ECR_REPO:$IMAGE_TAG" > imagedefinitions.json

      - echo Writing appspec.yaml...
      - |
        cat > appspec.yaml <<EOF
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: vamsi-task
        LoadBalancerInfo:
          ContainerName: vamsi-repo
          ContainerPort: 8080
EOF

      - echo Creating deployment package...
      - zip deployment.zip imagedefinitions.json appspec.yaml

      - echo Verifying deployment.zip contents...
      - unzip -l deployment.zip
      - echo "📄 appspec.yaml contents:"
      - cat appspec.yaml

      - echo Uploading deployment.zip to S3...
      - aws s3 cp deployment.zip s3://$S3_BUCKET/$S3_KEY --region $AWS_REGION

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yaml
    - deployment.zip
