version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    ECR_REPO: public.ecr.aws/z8i7v1n4/vamsi-repo
    CONTAINER_NAME: vamsi-repo
    S3_BUCKET: vamsi-deploy-artifacts
    IMAGEDEF_KEY: ecs/imagedefinitions.json
    APPSPEC_KEY: ecs/appspec.yaml

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo IMAGE_TAG=$IMAGE_TAG

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG $ECR_REPO:latest

  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push $ECR_REPO:$IMAGE_TAG
      - docker push $ECR_REPO:latest

      - echo Writing imagedefinitions.json...
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$ECR_REPO:$IMAGE_TAG" > imagedefinitions.json

      - echo Validating appspec.yaml from source...
      - cat appspec.yaml

      - echo Uploading imagedefinitions.json and appspec.yaml to S3...
      - aws s3 cp imagedefinitions.json s3://$S3_BUCKET/$IMAGEDEF_KEY --region $AWS_REGION
      - aws s3 cp appspec.yaml s3://$S3_BUCKET/$APPSPEC_KEY --region $AWS_REGION

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yaml
